/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Fechas;
import Controlador.producto;
import static Vista.CONTABILIDAD.contenedor;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class FACTURA extends javax.swing.JFrame {
    DefaultTableModel modelo;
    ImagenFondo ejemplo =  new ImagenFondo();
    /**
     * Creates new form FACTURA
     */
    public FACTURA() {
        this.setContentPane(ejemplo);
        initComponents();
        setLocationRelativeTo(null);
        
        Fechas f = new Fechas();
        
        lblFecha.setText(f.fechaActual());
        
        modelo=new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Nombre");
        modelo.addColumn("Descripción");
        modelo.addColumn("Categoría");
        modelo.addColumn("Precio");
        this.factura.setModel(modelo);
        this.factura.setBackground(Color.white);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel6 = new javax.swing.JLabel();
        txtsubtotal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtisv = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        factura = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtidcliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtnombrecliente = new javax.swing.JTextField();
        txttelcliente = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        btnbuscar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtNombreP = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        btnagregar2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        txtcerrar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1200, 700));
        setMinimumSize(new java.awt.Dimension(1200, 700));
        setPreferredSize(new java.awt.Dimension(1200, 700));
        setResizable(false);
        setSize(new java.awt.Dimension(1091, 692));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 51, 102));
        jButton2.setText("Regresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, 30));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 102));
        jLabel6.setText("Subtotal");
        jLayeredPane1.add(jLabel6);
        jLabel6.setBounds(760, 550, 60, 22);

        txtsubtotal.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLayeredPane1.add(txtsubtotal);
        txtsubtotal.setBounds(830, 550, 71, 25);

        jLabel7.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 102));
        jLabel7.setText("ISV");
        jLayeredPane1.add(jLabel7);
        jLabel7.setBounds(910, 550, 23, 22);

        txtisv.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLayeredPane1.add(txtisv);
        txtisv.setBounds(940, 550, 71, 25);

        jLabel8.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 102));
        jLabel8.setText("TOTAL");
        jLayeredPane1.add(jLabel8);
        jLabel8.setBounds(1020, 550, 43, 22);

        txttotal.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLayeredPane1.add(txttotal);
        txttotal.setBounds(1070, 550, 71, 25);

        factura.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 16)); // NOI18N
        factura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(factura);

        jLayeredPane1.add(jScrollPane1);
        jScrollPane1.setBounds(360, 280, 780, 250);

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 102));
        jLabel5.setText("ID Cliente");
        jLayeredPane1.add(jLabel5);
        jLabel5.setBounds(410, 140, 70, 22);

        txtidcliente.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLayeredPane1.add(txtidcliente);
        txtidcliente.setBounds(490, 140, 40, 25);

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 102));
        jLabel3.setText("Nombre del cliente");
        jLayeredPane1.add(jLabel3);
        jLabel3.setBounds(540, 140, 190, 22);

        txtnombrecliente.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLayeredPane1.add(txtnombrecliente);
        txtnombrecliente.setBounds(680, 140, 180, 25);

        txttelcliente.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 20)); // NOI18N
        txttelcliente.setForeground(new java.awt.Color(0, 51, 102));
        txttelcliente.setText("Teléfono");
        jLayeredPane1.add(txttelcliente);
        txttelcliente.setBounds(870, 140, 170, 22);

        jTextField3.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLayeredPane1.add(jTextField3);
        jTextField3.setBounds(940, 140, 120, 25);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setText("ID Producto");
        jLayeredPane1.add(jLabel1);
        jLabel1.setBounds(410, 190, 80, 22);

        txtId.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        txtId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdKeyTyped(evt);
            }
        });
        jLayeredPane1.add(txtId);
        txtId.setBounds(490, 190, 71, 25);

        btnbuscar.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 20)); // NOI18N
        btnbuscar.setForeground(new java.awt.Color(0, 51, 102));
        btnbuscar.setText("Buscar");
        btnbuscar.setPreferredSize(new java.awt.Dimension(99, 33));
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });
        jLayeredPane1.add(btnbuscar);
        btnbuscar.setBounds(580, 190, 99, 27);

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 102));
        jLabel4.setText("Producto:");
        jLayeredPane1.add(jLabel4);
        jLabel4.setBounds(690, 190, 66, 22);

        txtNombreP.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLayeredPane1.add(txtNombreP);
        txtNombreP.setBounds(780, 190, 280, 25);

        jLabel9.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 102));
        jLabel9.setText("Cantidad:");
        jLayeredPane1.add(jLabel9);
        jLabel9.setBounds(410, 230, 70, 22);

        txtCantidad.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLayeredPane1.add(txtCantidad);
        txtCantidad.setBounds(500, 230, 120, 25);

        jLabel10.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 102));
        jLabel10.setText("Precio:");
        jLayeredPane1.add(jLabel10);
        jLabel10.setBounds(650, 230, 60, 22);

        txtPrecio.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        txtPrecio.setEnabled(false);
        jLayeredPane1.add(txtPrecio);
        txtPrecio.setBounds(710, 230, 120, 25);

        btnagregar2.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 20)); // NOI18N
        btnagregar2.setForeground(new java.awt.Color(0, 51, 102));
        btnagregar2.setText("AGREGAR");
        btnagregar2.setPreferredSize(new java.awt.Dimension(99, 33));
        btnagregar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregar2ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(btnagregar2);
        btnagregar2.setBounds(880, 230, 99, 27);

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(251, 215, 48));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("FACTURA");
        jLayeredPane1.add(jLabel2);
        jLabel2.setBounds(356, 60, 790, 39);

        lblFecha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(255, 255, 255));
        lblFecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFecha.setText("Fecha:");
        jLayeredPane1.add(lblFecha);
        lblFecha.setBounds(350, 7, 700, 30);

        txtcerrar1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        txtcerrar1.setForeground(new java.awt.Color(0, 51, 102));
        txtcerrar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/iconcerrarsesionSMALL.png"))); // NOI18N
        txtcerrar1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        txtcerrar1.setLabel("Cerrar Sesión");
        txtcerrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcerrar1ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(txtcerrar1);
        txtcerrar1.setBounds(1040, 0, 150, 41);

        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed

        String ID = txtId.getText().trim();
        producto p;
        
        for (int i= 0; i < REGISTRARPRODUCTO.contenedor.size(); i++){
            p=(producto)REGISTRARPRODUCTO.contenedor.get(i);
            if (ID.equalsIgnoreCase(p.getSidproducto())){
                txtNombreP.setText(p.getDescripcion());
                txtPrecio.setText(p.getSprecio());
            }
        }  
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        MENUCAJERO frm = new MENUCAJERO();
        frm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtcerrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcerrar1ActionPerformed
        Login01 frm = new Login01();
        frm.setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcerrar1ActionPerformed

    private void txtIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdKeyTyped
        // TODO add your handling code here:
        int press = evt.getKeyChar();
        if (press == 10){
        String ID = txtId.getText().trim();
        producto p;
        
        for (int i= 0; i < REGISTRARPRODUCTO.contenedor.size(); i++){
            p=(producto)contenedor.get(i);
            if (ID.equalsIgnoreCase(p.getSidproducto())){
                txtNombreP.setText(p.getSnombreProd());
            }

        }
    }//GEN-LAST:event_txtIdKeyTyped
    }
    private void btnagregar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnagregar2ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FACTURA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FACTURA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FACTURA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FACTURA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FACTURA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagregar2;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JTable factura;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombreP;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JButton txtcerrar1;
    private javax.swing.JTextField txtidcliente;
    private javax.swing.JTextField txtisv;
    private javax.swing.JTextField txtnombrecliente;
    private javax.swing.JTextField txtsubtotal;
    private javax.swing.JLabel txttelcliente;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}

class ImagenFondo extends JPanel
{
    private Image imagen;
    public void paint (Graphics g)
    {
        imagen = new ImageIcon(getClass().getResource("/IMG/CAJERO.jpeg")).getImage();
        g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
        setOpaque(false);
        super.paint(g);
    }
}