
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Laptop
 */
public class JFrameCajeroBuscar extends javax.swing.JFrame {

    /**
     * Creates new form JFrameCajeroBuscar
     */
    public JFrameCajeroBuscar() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        //Crear icono autoajustable y asignarlo a un label
        ImageIcon imagen = new ImageIcon( "src\\IMG\\iconcerrarsesion.png");
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(lblcerrar.getWidth(),lblcerrar.getHeight(),Image.SCALE_DEFAULT));
        lblcerrar.setIcon(icono);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCajeroBuscar1 = new JPanelCajeroBuscar();
        lblcerrar = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        lbltipocajero = new javax.swing.JLabel();
        lblCajero1 = new javax.swing.JLabel();
        btnRegresar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);
        setState(6);

        btnRegresar.setText("Regresar");

        lbltipocajero.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        lbltipocajero.setForeground(new java.awt.Color(0, 0, 0));
        lbltipocajero.setText("DENIS ZELAYA");

        lblCajero1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblCajero1.setForeground(new java.awt.Color(0, 0, 0));
        lblCajero1.setText("DENIS ZELAYA");

        btnRegresar1.setText("Regresar");

        javax.swing.GroupLayout jPanelCajeroBuscar1Layout = new javax.swing.GroupLayout(jPanelCajeroBuscar1);
        jPanelCajeroBuscar1.setLayout(jPanelCajeroBuscar1Layout);
        jPanelCajeroBuscar1Layout.setHorizontalGroup(
            jPanelCajeroBuscar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCajeroBuscar1Layout.createSequentialGroup()
                .addGap(0, 833, Short.MAX_VALUE)
                .addComponent(lblcerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelCajeroBuscar1Layout.createSequentialGroup()
                .addGroup(jPanelCajeroBuscar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCajeroBuscar1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(lbltipocajero))
                    .addGroup(jPanelCajeroBuscar1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelCajeroBuscar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelCajeroBuscar1Layout.createSequentialGroup()
                    .addGap(35, 35, 35)
                    .addComponent(lblCajero1)
                    .addContainerGap(707, Short.MAX_VALUE)))
            .addGroup(jPanelCajeroBuscar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelCajeroBuscar1Layout.createSequentialGroup()
                    .addGap(35, 35, 35)
                    .addComponent(btnRegresar1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(718, Short.MAX_VALUE)))
        );
        jPanelCajeroBuscar1Layout.setVerticalGroup(
            jPanelCajeroBuscar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCajeroBuscar1Layout.createSequentialGroup()
                .addComponent(lblcerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(154, 154, 154)
                .addComponent(lbltipocajero, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRegresar)
                .addContainerGap(286, Short.MAX_VALUE))
            .addGroup(jPanelCajeroBuscar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelCajeroBuscar1Layout.createSequentialGroup()
                    .addGap(194, 194, 194)
                    .addComponent(lblCajero1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(350, Short.MAX_VALUE)))
            .addGroup(jPanelCajeroBuscar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCajeroBuscar1Layout.createSequentialGroup()
                    .addContainerGap(504, Short.MAX_VALUE)
                    .addComponent(btnRegresar1)
                    .addGap(32, 32, 32)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCajeroBuscar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCajeroBuscar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameCajeroBuscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameCajeroBuscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameCajeroBuscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameCajeroBuscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameCajeroBuscar().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnRegresar1;
    private JPanelCajeroBuscar jPanelCajeroBuscar1;
    private javax.swing.JLabel lblCajero1;
    private javax.swing.JLabel lblcerrar;
    private javax.swing.JLabel lbltipocajero;
    // End of variables declaration//GEN-END:variables
}
